### ISSUE TITLE
simplify hippocampal warping

### ISSUE THREAD

**Issue by jordandekraker** [myousif9/hippograd#1]
https://github.com/myousif9/hippograd/blob/cd29d0777ac0d563b3ac54cd249c0ba6130dcfd0/hippograd/workflow/rules/post_hippunfold.smk#L21

consider using https://www.humanconnectome.org/software/workbench-command/-surface-apply-warpfield

**Comment by myousif9** [comment]
I ended up retaining the previous method of transforming the surfaces since `wb_command -surface-apply-warpfield` requires the transform to be in a nifti format when fMRIPrep provides in and `.h5` file. So far I haven't found a simpler way to convert the transform to a nifti file

**Comment by jordandekraker** [comment]
Seems like a good solution
