### ISSUE TITLE
brainspace for affinity

### ISSUE THREAD

**Issue by jordandekraker** [myousif9/hippograd#2]
https://github.com/myousif9/hippograd/blob/cd29d0777ac0d563b3ac54cd249c0ba6130dcfd0/hippograd/workflow/rules/post_hippunfold.smk#L21

calcualte correlation matrix here, and use that as the input to Brainspace (it will know what to do!)

**Comment by myousif9** [comment]
The latest commit now uses brainspace to calculate affinity, gradients and align them to the reference gradient in one step. Currently correlation matrices and gradients are calculated in a single snakemake rule, would you think it would be worthwhile to split them into separate rules or just keep them as is?

**Comment by jordandekraker** [comment]
I think its fine, so you can avoid having to save and then reload the exact same data. Especially if you make good error logging :)
